#!/bin/bash

set -e


region="us-east-1"
s3_bucket="lambda.newecx.com"
template_file=template.yaml

echo "region=$region"

export AWS_DEFAULT_REGION=$region

cd "$(dirname ${BASH_SOURCE[0]})"

project_name="$(basename $(pwd))"

echo "project name: $project_name"

if [ -d tmp ]; then
  rm -rf tmp
fi

mkdir tmp

sam build -t template.yaml

sam package --output-template-file tmp/packaged.yaml --s3-bucket $s3_bucket

sam deploy --template-file tmp/packaged.yaml --stack-name $project_name --capabilities CAPABILITY_IAM

rm -rf tmp
rm -rf .aws-sam

echo ">>> done!"